# Generated by Django 3.0.6 on 2020-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200905_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
